"""Minimal Thai mark positioning for the robot's bitmap font.

The M5GFX VLW renderer draws code points one after another with no OpenType shaping,
so Thai tone marks collide with upper vowels (ที่, นี้) and marks overlap the stems of
ป ฝ ฟ ฬ. ``shape()`` rewrites those marks to private-use code points whose glyphs
``tools/make_vlw_font.py`` renders raised / shifted - the same idea as the old
Windows/Mac Thai PUA fonts. Text without Thai is returned unchanged.
"""
from __future__ import annotations

UPPER_VOWELS = "ัิีึื็ํ"  # ั ิ ี ึ ื ็ ํ
TONES = "่้๊๋์"  # ่ ้ ๊ ๋ ์
LOWER_VOWELS = "ฺุู"  # ุ ู ฺ
ASCENDERS = "ปฝฟฬ"  # ป ฝ ฟ ฬ
DESCENDERS = "ฎฏ"  # ฎ ฏ
SARA_AM = "ำ"  # ำ carries a nikhahit above, so a tone before it must sit high

# private-use variants (glyphs generated by tools/make_vlw_font.py)
TONE_HIGH = {c: chr(0xF700 + i) for i, c in enumerate(TONES)}
TONE_LEFT = {c: chr(0xF705 + i) for i, c in enumerate(TONES)}
TONE_HIGH_LEFT = {c: chr(0xF70A + i) for i, c in enumerate(TONES)}
UPPER_LEFT = {c: chr(0xF710 + i) for i, c in enumerate(UPPER_VOWELS)}
LOWER_DOWN = {c: chr(0xF718 + i) for i, c in enumerate(LOWER_VOWELS)}


def shape(text: str) -> str:
    out = []
    base = ""  # consonant the current marks sit on
    has_upper = False
    for i, ch in enumerate(text):
        if ch in UPPER_VOWELS:
            out.append(UPPER_LEFT[ch] if base in ASCENDERS else ch)
            has_upper = True
        elif ch in TONES:
            nxt = text[i + 1] if i + 1 < len(text) else ""
            high = has_upper or nxt == SARA_AM
            left = base in ASCENDERS
            table = (TONE_HIGH_LEFT if left else TONE_HIGH) if high else (TONE_LEFT if left else None)
            out.append(table[ch] if table else ch)
        elif ch in LOWER_VOWELS:
            out.append(LOWER_DOWN[ch] if base in DESCENDERS else ch)
        else:
            out.append(ch)
            base, has_upper = ch, False
    return "".join(out)
