"""Build the robot's Thai speech-balloon font (VLW, as read by M5GFX) from a TTF.

    python tools/make_vlw_font.py                       # writes firmware/stackchan/src/thai_font.cpp
    python tools/make_vlw_font.py --preview out.png     # also renders sample text the way M5GFX does

Glyphs: ASCII, Thai (U+0E01-0E5B), a few punctuation marks, and the private-use mark
variants that ``flybot.thai_text.shape`` emits (raised tones, marks shifted left of
ascender stems, lower vowels pushed below descenders). The balloon draws at text size
2, so the default 13 px source shows as 26 px.
"""
from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from flybot import thai_text as tt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TTF = ROOT / "firmware/stackchan/fonts/Sarabun-Regular.ttf"
DEFAULT_OUT = ROOT / "firmware/stackchan/src/thai_font.cpp"
EXTRA = "“”‘’…•°×–—"


class Glyph:
    def __init__(self, code: int, bitmap: bytes, w: int, h: int, adv: int, dy: int, dx: int):
        self.code, self.bitmap, self.w, self.h, self.adv, self.dy, self.dx = code, bitmap, w, h, adv, dy, dx


def render(font: ImageFont.FreeTypeFont, ch: str) -> Glyph:
    adv = round(font.getlength(ch))
    mask, (ox, oy) = font.getmask2(ch, mode="L", anchor="ls")
    if not (mask.size[0] and mask.size[1]):
        return Glyph(ord(ch), b"", 0, 0, adv, 0, 0)
    im = Image.frombytes("L", mask.size, bytes(mask))
    box = im.getbbox()
    if not box:
        return Glyph(ord(ch), b"", 0, 0, adv, 0, 0)
    im = im.crop(box)
    left, top = box[0], box[1]
    # VLW: dY = top of the bitmap above the baseline, dX = left edge relative to the cursor
    return Glyph(ord(ch), im.tobytes(), im.width, im.height, adv, -(oy + top), ox + left)


def variant(src: Glyph, code: int, up: int = 0, left: int = 0) -> Glyph:
    return Glyph(code, src.bitmap, src.w, src.h, src.adv, src.dy + up, src.dx - left)


def build(ttf: Path, size: int) -> tuple[list[Glyph], int, int]:
    font = ImageFont.truetype(str(ttf), size)
    chars = [chr(c) for c in range(0x20, 0x7F)] + [chr(c) for c in range(0x0E01, 0x0E5C)
                                                    if chr(c) not in "฻฼฽฾"] + list(EXTRA)
    glyphs = {ord(ch): render(font, ch) for ch in chars}

    def top(ch): return glyphs[ord(ch)].dy
    def right(ch): g = glyphs[ord(ch)]; return g.dx + g.w

    upper_top = max(top(c) for c in tt.UPPER_VOWELS)
    tone_bottom = min(glyphs[ord(c)].dy - glyphs[ord(c)].h for c in tt.TONES)
    raise_by = max(0, upper_top + 1 - tone_bottom)  # tone sits just above an upper vowel
    stem_left = -3  # ascender stems occupy the last ~2 px before the cursor
    lower_top = max(top(c) for c in tt.LOWER_VOWELS)
    desc_bottom = min(glyphs[ord(c)].dy - glyphs[ord(c)].h for c in tt.DESCENDERS)
    drop_by = max(0, lower_top - desc_bottom + 1)

    for c in tt.TONES:
        g = glyphs[ord(c)]
        shift = max(0, right(c) - stem_left)
        for table, up, left in ((tt.TONE_HIGH, raise_by, 0), (tt.TONE_LEFT, 0, shift),
                                (tt.TONE_HIGH_LEFT, raise_by, shift)):
            glyphs[ord(table[c])] = variant(g, ord(table[c]), up, left)
    for c in tt.UPPER_VOWELS:
        glyphs[ord(tt.UPPER_LEFT[c])] = variant(glyphs[ord(c)], ord(tt.UPPER_LEFT[c]), 0, max(0, right(c) - stem_left))
    for c in tt.LOWER_VOWELS:
        glyphs[ord(tt.LOWER_DOWN[c])] = variant(glyphs[ord(c)], ord(tt.LOWER_DOWN[c]), -drop_by, 0)

    ascent, descent = top("d"), -(glyphs[ord("p")].dy - glyphs[ord("p")].h)
    return sorted(glyphs.values(), key=lambda g: g.code), ascent, descent


def to_vlw(glyphs: list[Glyph], size: int, ascent: int, descent: int) -> bytes:
    out = struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent)
    for g in glyphs:
        out += struct.pack(">7i", g.code, g.h, g.w, g.adv, g.dy, g.dx, 0)
    for g in glyphs:
        out += g.bitmap
    return out


def write_cpp(data: bytes, path: Path, ttf: Path, size: int) -> None:
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    path.write_text(
        f"// Generated by tools/make_vlw_font.py from {ttf.name} at {size} px - do not edit.\n"
        f"// Font: Sarabun (SIL Open Font License 1.1, see firmware/stackchan/fonts/OFL.txt)\n"
        '#include "thai_font.h"\n\n'
        f"const size_t thai_font_vlw_len = {len(data)};\n"
        "const uint8_t thai_font_vlw[] PROGMEM = {\n  " + ",\n  ".join(rows) + "\n};\n")


def preview(glyphs: list[Glyph], lines: list[str], path: Path, scale: int = 2) -> None:
    """Draw like M5GFX's VLW renderer: bitmap at (x + dX, baseline - dY), x += xAdvance."""
    table = {g.code: g for g in glyphs}
    max_ascent = max(g.dy for g in glyphs if g.code > 0x20)
    max_descent = max(g.h - g.dy for g in glyphs if g.code > 0x20)
    line_h = max_ascent + max_descent + 2
    width = 8 + max(sum(table.get(ord(c), table[0x20]).adv for c in tt.shape(t)) for t in lines)
    img = Image.new("L", (width, line_h * len(lines) + 4), 255)
    for row, text in enumerate(lines):
        x, base = 4, 2 + row * line_h + max_ascent
        for ch in tt.shape(text):
            g = table.get(ord(ch), table[0x20])
            if g.w:
                glyph = Image.frombytes("L", (g.w, g.h), g.bitmap)
                img.paste(0, (x + g.dx, base - g.dy), glyph)
            x += g.adv
    img.resize((img.width * scale, img.height * scale), Image.NEAREST).save(path)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", type=Path, default=DEFAULT_TTF)
    ap.add_argument("--size", type=int, default=13)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--preview", type=Path)
    args = ap.parse_args()
    glyphs, ascent, descent = build(args.ttf, args.size)
    data = to_vlw(glyphs, args.size, ascent, descent)
    write_cpp(data, args.out, args.ttf, args.size)
    print(f"{len(glyphs)} glyphs, {len(data)} bytes -> {args.out}")
    if args.preview:
        preview(glyphs, ["สวัสดีครับ ที่นี่", "น้ำ ปี่ ฟื้น ปั้น ฎุ ฏู", "อีก 10 นาที ประชุม HIS",
                         "Meeting in 10 min!"], args.preview)
        print(f"preview -> {args.preview}")


if __name__ == "__main__":
    main()
